
class Graphic

  def hangman_graphic
      case @amount_wrong_turns
      when 0
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""

        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"
        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      |        |"
        puts "               |"
        puts "      0".green + "        |"
        puts "     \\|/".green + "       |"
        puts "      |".green + "        |"
        puts "     / \\".green + "       |"
        puts "    ============"
        puts "      "

      when 1
                puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"
        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      0".green + "        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
        puts "      "

      when 2
                puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"
        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      0".green + "        |"
        puts "      |".green + "        |"
        puts "      |".green + "        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
        puts "      "
      when 3
                puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"

        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      0".green + "        |"
        puts "      |/".green + "       |"
        puts "      |".green + "        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
        puts "      "
      when 4
                puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"

        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      0".green + "        |"
        puts "     \\|/".green + "       |"
        puts "      |".green + "        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
        puts "      "
      when 5
                puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"
        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      0".green + "        |"
        puts "     \\|/".green + "       |"
        puts "      |".green + "        |"
        puts "     /".green + "         |"
        puts "               |"
        puts "               |"
        puts "    ============"
        puts "      "
      when 6
                puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"

        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      0".red + "        |"
        puts "     \\|/".red + "       |"
        puts "      |".red + "        |"
        puts "     / \\".red + "       |"
        puts "               |"
        puts "               |"
        puts "    ============"
        puts "      "
      end
    end
    def hangman_graphic_won
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      |        |"
        puts "               |"
        puts "      0".green + "        |"
        puts "     \\|/".green + "       |"
        puts "      |".green + "        |"
        puts "     / \\".green + "       |"
        puts "    ============"
        puts "      "
    end

    def hangman_graphic_start
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      0".yellow
        puts "     \\|/".yellow
        puts "      |".yellow 
        puts "     / \\".yellow 
        puts ""
        puts ""
        puts ""
        puts ""

        sleep(0.5)
                puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "  THE " + "HANGMAN ".yellow + "GAME"
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      0".green
        puts "     \\|-".green
        puts "      |".green 
        puts "     / \\".green 
        puts ""
        puts ""
        puts ""
        puts ""

        sleep(0.5)
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""

        puts "  THE " + "HANGMAN ".yellow + "GAME"
        puts "      __________"
        puts "      |        |"
        puts "      |        |"
        puts "               |"
        puts "      0".green + "        |"
        puts "     \\|/".green + "       |"
        puts "      |".green + "        |"
        puts "     / \\".green + "       |"
        puts "    ============"
        puts ""
        puts "      "

        
    end
end
