
class Graphic

  def hangman_graphic
      case @amount_wrong_turns
      when 0
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""

        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"
        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      |        |"
        puts "               |"
        puts "      0".green + "        |"
        puts "     \\|/".green + "       |"
        puts "      |".green + "        |"
        puts "     / \\".green + "       |"
        puts "    ============"
        puts "      "

      when 1
                puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"
        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      0".green + "        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
        puts "      "

      when 2
                puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"
        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      0".green + "        |"
        puts "      |".green + "        |"
        puts "      |".green + "        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
        puts "      "
      when 3
                puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"

        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      0".green + "        |"
        puts "      |/".green + "       |"
        puts "      |".green + "        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
        puts "      "
      when 4
                puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"

        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      0".green + "        |"
        puts "     \\|/".green + "       |"
        puts "      |".green + "        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
        puts "      "
      when 5
                puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"
        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      0".green + "        |"
        puts "     \\|/".green + "       |"
        puts "      |".green + "        |"
        puts "     /".green + "         |"
        puts "               |"
        puts "               |"
        puts "    ============"
        puts "      "
      when 6
                puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME ---- 1. save, 2. main menu, 3. quit"

        puts ""
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      0".red + "        |"
        puts "     \\|/".red + "       |"
        puts "      |".red + "        |"
        puts "     / \\".red + "       |"
        puts "               |"
        puts "               |"
        puts "    ============"
        puts "      "
      end
    end
    def hangman_graphic_won
        puts "     ❤".red + " = #{lives_left} | Letters Guessed -> [ #{self.letters_guessed.join(" ")} ]"
        puts "      __________"
        puts "      |        |"
        puts "      |        |"
        puts "               |"
        puts "      0".green + "        |"
        puts "     \\|/".green + "       |"
        puts "      |".green + "        |"
        puts "     / \\".green + "       |"
        puts "    ============"
        puts "      "
    end

    def hangman_graphic_start
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      0".yellow
        puts "     \\|/".yellow
        puts "      |".yellow 
        puts "     / \\".yellow 
        puts ""
        puts ""
        puts ""
        puts ""

        sleep(0.5)
                puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "  THE " + "HANGMAN ".yellow + "GAME"
        puts "      "
        puts "      "
        puts "      "
        puts "      "
        puts "      0".green
        puts "     \\|-".green
        puts "      |".green 
        puts "     / \\".green 
        puts ""
        puts ""
        puts ""
        puts ""

        sleep(0.5)
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""

        puts "  THE " + "HANGMAN ".yellow + "GAME"
        puts "      __________"
        puts "      |        |"
        puts "      |        |"
        puts "               |"
        puts "      0".green + "        |"
        puts "     \\|/".green + "       |"
        puts "      |".green + "        |"
        puts "     / \\".green + "       |"
        puts "    ============"
        puts ""
        puts "      "

        
    end

    def game_stats
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts "---------------------"
      puts "-                   -"
      puts "    "+"#{self.user_name.upcase}".yellow + "       "
      puts "-                   -"
      puts "-                   -"
      puts "-    GAMES WON      -"
      puts "-        "+ "#{self.games_won}".green + "          -"
      puts "-                   -"
      puts "-    GAMES LOST     -"
      puts "-        " + "#{self.games_lost}".red + "          -"
      puts "-                   -"
      puts "---------------------"
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
      puts ""
    end

    def lost_the_game
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""

        puts "                      YOU HAVE LOST".red
        puts ""
        puts ""
        puts ""
        puts "                       The word was"
        puts ""
        puts ""
        puts "                        " + random_word.upcase.green    
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""

        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""

        sleep(3)
        hangman_graphic
        puts space
        
        puts space
        puts "    "
        puts "YOU SHOULD TRY IT AGAIN!"
        puts space
        self.games_lost += 1
        reset
        save_game
        game_flow
    end

    def won_the_game
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""

        puts "                      YOU HAVE WON!".green
        puts ""
        puts ""
        puts ""
        puts "                       The word was"
        puts ""
        puts ""
        puts "                        " + random_word.upcase.green    
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""

        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""
        puts ""

        sleep(3)
        hangman_graphic_won
        display_lives_available
        puts "       "
        puts "THE WORD WAS:"
        puts "       "
        puts "            " + random_word.upcase.green
        puts "       "
        puts "       "
        self.games_won += 1
        reset
        save_game
        game_flow
  end

  def main_menu
    puts ""
    puts  "          MAIN MENU"
    puts "------------------------------- \\"
    puts "|                             -| |"
    puts "| 1. SELECT/CREATE NEW USER   -| |"
    puts "| 2. START PLAYING            -| |"        
    puts "| 3. VIEW YOUR SCORES         -| |" 
    puts "| 4. VIEW LEADERBOARD         -| |"
    puts "| 5. QUIT                     -| |"
    puts "-------------------------------\\ |"
    puts "--------------------------------\\|"
    puts ""
    puts ""
    puts ""
    puts ""
    puts ""
    puts ""
    puts ""
    puts ""
        puts "  THE " + "HANGMAN ".yellow + "GAME"
        puts ""
        puts "        ❤".red + " = #{lives_left}"
        puts "      __________"
        puts "      |        |"
        puts "      |        |"
        puts "               |"
        puts "      0".green + "        |"
        puts "     \\|/".green + "       |"
        puts "      |".green + "        |"
        puts "     / \\".green + "       |"
        puts "    ============"
        puts "      "
  end

    def leaderboard
    # binding.pry
    sorted_users = users_in_memory.sort_by {|username, attributes| attributes["games_won"]}.reverse
    puts "------------------------------------------"
    puts "|USERNAME |    GAMES WON  |    GAMES LOST |"
    i = 1
    sorted_users.each do |key, values|
    puts "|                                         |"
      puts " #{i.to_s} - " + key + "          " +"#{values['games_won']}".green + "            " + "#{values['games_lost']}".red+"        "
      i += 1
    end
    puts "-------------------------------------------"
    sleep(3)
    user_choice
  end

    def display_history
    puts "Here's how many games you have WON: " + "#{self.games_won}".green
    puts "Here's how many games you have LOST: " + "#{self.games_lost}".red
  end

    def winner_message
      puts "#{['YES!!', 'LET\'S GIT IT!!!', 'GIT OFF MY LAWN!!!', 'WOW! YOU\'RE AMAZING!'].sample}"
      puts "       "
  end

  def loser_message
      puts "#{['OOPS!', 'WRONG LETTER!', 'WRONG!', "BAD CHOICE!", 'INCORRECT!'].sample}"
      puts "       "
  end

    def recurrent_message
    # puts "PLEASE ENTER A LETTER TO BEGIN:"
    puts space
    puts "Here are the letters that you've guessed: #{self.letters_guessed} "
    puts space
    puts "        ❤".red + " = #{lives_left}"
    hangman_graphic
    puts "    "+ spaces
  end

    def invalid_message_restart
    puts "YOUR ENTRY WAS INVALID, PLEASE TRY AGAIN"
    user_choice
  end

    def space
    "      "
  end

end
