
class Graphic

  def hangman_graphic
      case @amount_wrong_turns
      when 0
        puts ""
        puts "      __________"
        puts "      |        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
      when 1
        puts ""
        puts "      __________"
        puts "      |        |"
        puts "      0        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
      when 2
        puts ""
        puts "      __________"
        puts "      |        |"
        puts "      0        |"
        puts "      |        |"
        puts "      |        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
      when 3
        puts ""
        puts "      __________"
        puts "      |        |"
        puts "      0        |"
        puts "      |/       |"
        puts "      |        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
      when 4
        puts ""
        puts "      __________"
        puts "      |        |"
        puts "      0        |"
        puts "     \\|/       |"
        puts "      |        |"
        puts "               |"
        puts "               |"
        puts "               |"
        puts "    ============"
      when 5
        puts ""
        puts "      __________"
        puts "      |        |"
        puts "      0        |"
        puts "     \\|/       |"
        puts "      |        |"
        puts "     /         |"
        puts "               |"
        puts "               |"
        puts "    ============"
      when 6
        puts ""
        puts "      __________"
        puts "      |        |"
        puts "      0        |"
        puts "     \\|/       |"
        puts "      |        |"
        puts "     / \\       |"
        puts "               |"
        puts "               |"
        puts "    ============"
      end
    end
end
